### ISSUE TITLE
UIColor + Hex 에서 hexString 산출 오류 

### ISSUE THREAD

**Issue by delmaSong** [codesquad-member-2020/issue-tracker-02#113]
![스크린샷 2020-06-20 오전 12 57 04](https://user-images.githubusercontent.com/40784518/85153444-2f318d00-b291-11ea-9e9a-4eee983b3454.png)

**Comment by corykim0829** [comment]
어이쿠... 월요일에 같이 확인하면서 수정해야할 것 같네요 ㅜ

**Comment by corykim0829** [comment]
램덤 칼라를 만들 때 어떻게 만드냐에 따라서 달라지는 것 같아요.

**Comment by corykim0829** [comment]
https://velog.io/@rollmind/%EC%BD%94%EB%93%9C%ED%83%90%ED%97%98%EA%B8%B0-UIColor-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EC%96%B4%EC%85%88%EB%B8%94%EB%A6%AC?fbclid=IwAR3KnLT6lHRU29kTcxcYYx6QpwaLnPcxhLsmat6zf-MOQIG4zub7qrt5lGw

**Comment by corykim0829** [comment]
해결하여 클로즈합니다.
