### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-member-2020/issue-tracker-02#4]
> API, json 에 대한 모든 내용은 별도의 이슈 없이 Swagger 로 관리됩니다

http://52.79.81.75:8080/swagger-ui.html

- Swagger 에 있는 모든 API 와 json 에 대해 최대한 친절한 설명을 달아드릴 예정입니다
부족하거나 이해가 안되는 부분이 있다면 기록 부탁드립니다

![image](https://user-images.githubusercontent.com/55722186/84064434-8e73df80-a9fd-11ea-803d-96c46c3a0db3.png)

**Comment by delmaSong** [comment]
[GET] /api/issues/

issues 의 `content`를 `description`으로 필드명 변경 요청드립니다 
labesl의 `content`를 `description`으로 필드명 변경 요청드립니다

**Comment by corykim0829** [comment]
POST /api/issues/{issueId}
위 요청에서 label filed명 중 `content`를 `description`으로 변경해주세요!

**Comment by Hyune-c** [comment]
@corykim0829 @delmaSong 

본 이슈는 딱히 Open 을 유지하지 않아도 될 듯 합니다
각 API 별 요청 사항은 대분류 되어 있는 각 이슈의 코멘트로 기록 부탁드립니다
