### ISSUE TITLE
IssuesCollectionView layout 깨짐 현상

### ISSUE THREAD

**Issue by delmaSong** [codesquad-member-2020/issue-tracker-02#46]
## 문제

처음에 시작할 때 IssuesCollectionView의 cellSize가 제대로 적용되지 않아서 깨지는 현상이 발생
그러나, 다른 tap에 갔다가 다시 돌아오면 다시 정상적으로 적용된다.

## 공부해야하는 점
- tab 전환 시, view controller life cycle은 어떻게 되는가?

**Comment by corykim0829** [comment]
[UITabBarController](https://developer.apple.com/documentation/uikit/uitabbarcontroller)

**Comment by corykim0829** [comment]
TabBar life cycle 문제는 아니였습니다.
dynamic height를 정상적으로 구현하니 해결되었습니다.
해결하여 클로즈하겠습니다.
