### ISSUE TITLE
다크모드 적용 

### ISSUE THREAD

**Issue by delmaSong** [codesquad-member-2020/issue-tracker-02#50]
다크모드에서 메인 키컬러로 사용하고 있는 청록색이 꽤 어두운데 다른 컬러로 변경할지 여부 논의 필요
  방안 1. keyColors에서 밝은 다른색으로 변경되도록 한다
<img src = "https://user-images.githubusercontent.com/40784518/84629929-11c59180-af26-11ea-881e-1fb4a38a94fd.png" width = 20% /> <img src = "https://user-images.githubusercontent.com/40784518/84629963-1f7b1700-af26-11ea-8703-a950e8f6b0e9.png" width = 20% />

  방안 2. 동일한 색상에 명도와 채도만 높인 컬러로 지정한다
<img src = "https://user-images.githubusercontent.com/40784518/84630003-328de700-af26-11ea-9cf7-2f14c65999f9.png" width = 20% />

  방안 3. 변경 없이 그대로 사용한다
<img src = "https://user-images.githubusercontent.com/40784518/84628930-77b11980-af24-11ea-82b7-49e54b2a614b.png" width = 20% />

**Comment by corykim0829** [comment]
방안2번에서 Title textColor도 하얀색으로하면 좋을 것 같아요!

**Comment by delmaSong** [comment]
해당 이슈 구현 완료해 close합니다
